### ISSUE TITLE
Segmentation Fault when trying to apply Tshift

### ISSUE THREAD

**Issue by DradeAW** [billkarsh/CatGT#1]
Hi,

I'm trying to use CatGT to take care of the multiplexing time shift on both the AP and LFP channels.
I am on Ubuntu 20.04, and the recording was made on another computer running on Windows 10.

My folder architecture is:
```
- Frequency_Recording // Containing all recording from SpikeGLX and OpenEphys
--- test_capacitive_g0
----- test_capacitive_g0_imec0
------- test_capacitive_g0_t0.imec0.ap.bin
------- test_capacitive_g0_t0.imec0.ap.meta
------- test_capacitive_g0_t0.imec0.lf.bin
------- test_capacitive_g0_t0.imec0.lf.meta
----- test_capacitive_g0_t0.nidq.bin
----- test_capacitive_g0_t0.nidq.meta
```

First, I needed to rename the folder `test_capacitive_g0_imec0` to remove `_imec0`, otherwise CatGT would give me the following error in the logs: `Meta file not found '/mnt/hdd/data/Frequency_Recording/test_capacitive_g0/test_capacitive_g0_imec0/test_capacitive_g0/test_capacitive_g0_t0.imec0.ap.meta'.`

After renaming, I ran the command `sh runit.sh '-dir=/mnt/hdd/data/Frequency_Recording/test_capacitive_g0 -run=test_capacitive -g=g0, -t=t0 -ap -lf -prb=0 -dest=./output'`
Which resulted in a message `Segmentation Fault`.

Here are the logs:
```bash
$ cat CatGT.log
[Thd 140570119120704 CPU 0 4/06/23 10:31:28.785] Cmdline: CatGT -dir=/mnt/hdd/data/Frequency_Recording/test_capacitive_g0 -run=test_capacitive -g=0 -t=0 -ap -lf -prb=0 -dest=./output
```

Is there something wrong with my arguments?

Thank you,
Aurélien W.

**Comment by billkarsh** [comment]
CatGT understands the folder naming used by SpikeGLX. You don't have to rename folders, rather, use the -prb_fld option.  The crash is a known issue in 3.7. It will be fixed in 3.8 which will be released by 4/7/2023.

**Comment by DradeAW** [comment]
Thank you,

The latest commit solved the crash and now runs correctly.

However the `-prb_fld` did not work, and renaming the folder still seemed to be required.

**Comment by DradeAW** [comment]
My bad, I needed to take away the `/test_capacitive_g0` at the end of the `-dir` argument.

Thank you!
