### ISSUE TITLE
Release of Version 4.4 on SpikeGLX GitHub Page

### ISSUE THREAD

**Issue by jiumao2** [billkarsh/CatGT#3]
Hi Bill,

Thank you for creating this amazing tool! It works perfectly with SpikeGLX recordings. I noticed that version 4.4 is available in this repository, but the latest version listed on the SpikeGLX GitHub page is still 4.3 (https://billkarsh.github.io/SpikeGLX/#catgt).

Do you have any plans to release version 4.4 soon?

**Comment by billkarsh** [comment]
I'm still working on the feature set of 4.4. I'll release it around SfN.

**Comment by billkarsh** [comment]
I'm releasing/publishing CatGT version 4.4 today. Look for it on download page.

**Comment by jiumao2** [comment]
Great! Thanks for the prompt information!
